### ISSUE TITLE
Perhaps we don't need to use ICU?

### ISSUE THREAD

**Issue by arunvickram** [alerque/icu-lua#2]
If all that we're looking for digit mapping, I think trying to leverage all of ICU at once may be a massive undertaking that may not be worth the hassle. I just noticed that you were experimenting with auto-generating the bindings, and I figured I would raise this issue here.

**Comment by alerque** [comment]
Never-mind digit mapping, I've needed lots of different bits of ICU before. SILE even *has* a bindings library with hand coded bindings for the functions we need there. I've had other projects that need this too and even called out to JS or Rust bindings to get the results I needed and stuffed the results into Lua. This project is because a more generic approach that covers the whole API surface would be much more useful. Yes it is a massive undertaking. My first attempts at auto-generating bindings haven't gone well either, but I'm still hopeful there will be a way to pull it off.
